# https://doc.rust-lang.org/cargo/reference/config.html

[alias]
upload = "flash --chip STM32F303K8Tx"

[build]
# https://www.st.com/en/microcontrollers-microprocessors/stm32f303k8.html
# https://www.arm.com/ja/products/silicon-ip-cpu/cortex-m/cortex-m4
# https://doc.rust-lang.org/nightly/rustc/platform-support/thumbv7em-none-eabi.html
target = "thumbv7em-none-eabihf"

[profile.dev]
opt-level = "s"
debug = "none"
strip = "debuginfo"

[target.thumbv7em-none-eabihf]
# https://probe.rs/docs/tools/probe-rs/#run
runner = "probe-rs run --chip STM32F303K8Tx"
linker = "arm-none-eabi-gcc"
rustflags = [
    # https://defmt.ferrous-systems.com/setup#linker-script
    "-Clink-arg=-Tdefmt.x",
    # https://docs.rs/cortex-m-rt/0.7.3/cortex_m_rt/#an-example
    "-Clink-arg=-Tlink.x",
    # https://assistc.hatenablog.jp/entry/arm-gcc-compile-option
    "-Clink-args=-mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16",
    "-Clink-args=-nostdlib -nodefaultlibs",
]
