name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get -qq install 'gcc-arm-none-eabi=15:10.3*'
      - run: cargo build
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features -- -D warnings
